sudo: required

services:
  - docker
  
install:
  - docker build -t softasap/alpine_python:test python/python-2.7

script:
  - docker run --name alpine_python -d softasap/alpine_python:test && echo "RUN OK"
